baseURL: /
languageCode: es
title: 'CV Renán Pulquillanca'
theme: hugo-devresume-theme
googleAnalytics: UA-XXXXXXX-Y
params:
  author: renan
  awards:
    enable: yes
    list:
      - body: Microsoft lorem ipsum
        date: '2019'
        name: Award Lorem Ipsum
      - body: Oracle Aenean
        date: '2017'
        name: Award Donec Sodales
  contact:
    enable: yes
    list:
      - icon: fas fa-phone-square
        text: +569 49463457
        url: tel:#
      - icon: fas fa-envelope-square
        text: renan.pulquillanca@gmail.com
        url: mailto:#
      - icon: fas fa-globe
        text: www.yourwebsite.com
        url: '#'
    location: Santiago de Chile
  description: DevResume - Bootstrap 4 Resume/CV Template For Software Developers
  education:
    enable: yes
    list:
      - dates: 2014 - 2020
        degree: Ingeniería Civil Química
        university: Universidad de Chile
  
      - dates: 2012 - 2016
        degree: Licenciatura en Ciencias de la Ingeniería Mención Minería y Metalurgia Extractiva
        university: Universidad de Chile
      - dates: 2012 - 2016
        degree: Licenciatura en Ciencias de la Ingeniería Mención Química
        university: Universidad de Chile
       
  experience:
    enable: yes
    list:
      - company: Gestión Ambiental S.A.
        dates: 202O- Actualidad
        details: Role description goes here ipsum dolor sit amet, consectetuer adipiscing
          elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque
          penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec
          quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede
          justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing
          elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque
          penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec
          quam felis.
        items:
          - details: Lorem ipsum dolor sit amet, consectetuer.
          - details: Aenean commodo ligula eget dolor.
          - details: Etiam ultricies nisi vel augue.
        title: Ingeniero de Proyectos
      - company: Apple
        dates: 2016 - 2019
        details: Role description goes here ipsum dolor sit amet, consectetuer adipiscing
          elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque
          penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec
          quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede
          justo, fringilla vel.
        items:
          - details: Lorem ipsum dolor sit amet, consectetuer.
          - details: Aenean commodo ligula eget dolor.
        title: Lead Software Developer
      - company: Dropbox
        dates: 2014 - 2016
        details: Role description goes here ipsum dolor sit amet, consectetuer adipiscing
          elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque
          penatibus et magnis dis parturient montes, nascetur ridiculus mus.
        title: Senior Software Developer
      - company: Uber
        dates: 2013 - 2014
        details: Role description goes here ipsum dolor sit amet, consectetuer adipiscing
          elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque
          penatibus.
        title: Senior Developer
      - company: Amazon
        dates: 2014 - 2016
        details: Role description goes here ipsum dolor sit amet, consectetuer adipiscing
          elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque
          penatibus et magnis dis parturient montes, nascetur ridiculus mus.
        title: Backend Developer
      - company: Startup
        dates: 2013 - 2014
        details: Role description goes here ipsum dolor sit amet, consectetuer adipiscing
          elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque
          penatibus.
        title: Frontend Developer
  information:
    enable: yes
    list:
      - items:
          - details: 2018 · Lorem Ipsum
          - details: 2016 · Sed Fringilla
        title: Papers
      - details: Climbing, Snowboarding, Photography, Travelling
        title: Interests
  interests:
    enable: yes
    list:
      - name: Climbing
      - name: Snowboarding
      - name: Photography
      - name: Travelling
  languages:
    enable: yes
    list:
      - level: Native
        name: Español
      - level: Professional
        name: Inglés
  primaryColor: '#54B689'
  profile:
    avatar: RP.png
    enable: yes
    name: Renán Pulquillanca
    tagline: Ingeniero Civil Químico
  projects:
    enable: yes
    list:
      - meta: Open Source
        tagline: You can use this section for your side projects. Lorem ipsum dolor
          sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
          Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes,
          nascetur ridiculus mus.
        title: Project Lorem Ipsum
      - meta: Open Source
        tagline: You can use this section for your side projects. Cras dapibus. Vivamus
          elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula,
          porttitor eu, consequat vitae, eleifend ac, enim.
        title: Project Sed Fringilla
      - meta: Open Source
        tagline: You can use this section for your side projects. Cras dapibus. Vivamus
          elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula,
          porttitor eu, consequat vitae, eleifend ac, enim.
        title: Project Praesent
  skills:
    enable: yes
    list:
      - items:
          - details: R/Python/Matlab/SQL
          - details: PowerBi/PowerApps/PowerAutomate
          - details: Excel/Access/MS SQL
          - details: PostgreSQL/MySQL Server
          - details: Arcgis/Qgis
          - details: Design and implement database structures
          - details: Lead and deliver complex software systems
        title: Technical
      - items:
          - details: Effective communication
          - details: Team player
          - details: Strong problem solver
          - details: Good time management
        title: Professional
  social:
    enable: yes
    list:
      - icon: fab fa-github-square
        title: Rpulqui
        url: //github.com/Rpulqui
      - icon: fab fa-linkedin
        title: Rpulquillanca
        url: //linkedin.com/in/rpulquillanca
      - icon: fab fa-twitter-square
        title: '@username'
        url: //twitter.com/username
  summary:
    enable: yes
    text: Profesional con experiencia en procesamiento, validación e interpretación de datos hidroquímicos de aguas superficiales y subterráneas de diferentes proyectos mineros. Encargado de la elaboración de líneas de base de calidad de aguas, y, posee participación en Declaraciones y Estudios de Impacto Ambiental. Posee experiencia en modelación y simulación de procesos con lenguajes de programación tales como Matlab y Python. Además, posee sólidos conocimientos en extracción, importación, manipulación, limpieza y visualización de datos en R, Python, Power BI y SQL. Se ha desempeñado como administrador de bases de datos en SGA y tiene habilidades de programación para consultas avanzadas en SQL. Ha desarrollado aplicaciones en PowerApps y flujos de trabajo en PowerAutomate para control de proyectos, gestión de carga laboral, gestión técnica unidad de recursos hídricos y sistema gestión de calidad. Además, cuenta con conocimientos de normativas ambientales relacionadas a la calidad del agua y residuos industriales. Por último, posee experiencia en sistemas de información geográfica utilizando R y Arcgis. 
  textPrimaryColor: '#292929'
