baseURL: /
languageCode: es
title: 'CV Renán Pulquillanca'
theme: hugo-devresume-theme
googleAnalytics: UA-XXXXXXX-Y
params:
  author: renan
  awards:
    enable: no
    list:
      - body: Microsoft lorem ipsum
        date: '2019'
        name: Award Lorem Ipsum
      - body: Oracle Aenean
        date: '2017'
        name: Award Donec Sodales
  contact:
    enable: yes
    list:
      - icon: fas fa-phone-square
        text: +569 49463457
        url: tel:#
      - icon: fas fa-envelope-square
        text: renan.pulquillanca@gmail.com
        url: mailto:#
      - icon: fab fa-linkedin
        text: Rpulquillanca
        url: //linkedin.com/in/rpulquillanca
      #- icon: fas fa-globe
       # text: www.yourwebsite.com
        #url: '#'
    location: Santiago de Chile
  description: DevResume - Bootstrap 4 Resume/CV Template For Software Developers
  education:
    enable: yes
    list:
      - dates: 2014 - 2020
        degree: Ingeniería Civil Química
        university: Universidad de Chile
  
      - dates: 2012 - 2016
        degree: Licenciatura en Ciencias de la Ingeniería Mención Minería y Metalurgia Extractiva
        university: Universidad de Chile
      - dates: 2012 - 2016
        degree: Licenciatura en Ciencias de la Ingeniería Mención Química
        university: Universidad de Chile
       
  experience:
    enable: yes
    list:
      - company: Gestión Ambiental S.A.
        dates: 202O - Actualidad
        details: Role description goes here ipsum dolor sit amet, consectetuer adipiscing
          elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque
          penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec
          quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede
          justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing
          elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque
          penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec
          quam felis.
        items:
          - details: Encargado de elaborar líneas de base de calidad de aguas para proyectos con tramitación ambiental.
          - details: Desarrollo de aplicaciones en PowerApps, automatización de flujos de trabajo en PowerAutomate, y, elaboración de reportes y dashboards en PowerBI.
          - details: Responsable del procesamiento, validación e interpretación de datos hidroquímicos de aguas superficiales y subterráneas de diferentes proyectos mineros. 
                     Además, encargado de diseñar y construir bases de datos en Azure SQL Server y crear flujos de trabajo para la automatización de los resultados.
          - details: Encargado de realizar el modelo de mezcla entre el efluente de la estación depuradora de aguas servidas y el río Valdivia, y, responsable de evaluar el cumplimiento de la normativa de calidad de aguas
                     para las concentraciones finales de los elementos conservativos.
          - details: Responsable de determinar la concentración teórica de compuestos organofosforados en la salmuera de reinyección y evaluar el cumplimiento de la normativa chilena.
                     Además, responsable de identificar los potenciales impactos ambientales en la zona de SVAHT producto de la reinyección de compuestos orgánicos en la salmuera. 
                     Este trabajo se enmarcó en el Estudio de impacto ambiental para el Proyecto de Sales Maricunga.
          - details: Responsable de determinar la tasa de infiltración en sistemas lagunares del Salar de Atacama mediante sensores de temperatura y ecuaciones analíticas derivadas de la transferencia de calor. 
                     Se utiliza el software MATLAB para el procesamiento de las señales de temperatura y para la estimación de la velocidad vertical de flujo (_q_). Además, se realizan balances hídricos mediante datos 
                     de una estación meteorológica, imágenes satelitales e información de flujos superficiales medidos en terreno. Todo este proceso se automatiza en el lenguaje R.
        title: Ingeniero de Proyectos
      - company: Fresenius Kabi
        dates: ene 2018 - mar 2018
        details: Responsable de realizar un Dashboard en Excel para la gerencia de producción de la empresa, en la cual se exhiben los indicadores KPI más importantes para el proceso productivo. 
                 Además, se estima la eficiencia general de producción de diversos equipos (OEE) mediante información histórica de los lotes producidos por las máquinas.
        title: Ayudante de Ingeniería
      - company: Codelco
        dates: ene 2015 - mar 2015
        details: En el de área de planta de la división Radomiro Tomic fue el encargado de validar un modelo de Machine Learning para estimación de la recuperación de cobre en las pilas de lixiviación,
                 para futuros escenarios de explotación de mineral tanto de minerales oxidados y sulfurados.
        title: Ayudante de Ingeniería
      - company: Tutor Uchile
        dates: 2014 - 2020
        details: Responsable de dictar clases particulares de Cálculo, Álgebra, Mecánica de sólidos, Matemáticas, Física y Química.
        title: Profesor de Clases Particulares
  information:
    enable: no
    list:
      - items:
          - details: 2018 · Lorem Ipsum
          - details: 2016 · Sed Fringilla
        title: Papers
      - details: Climbing, Snowboarding, Photography, Travelling
        title: Interests
  interests:
    enable: yes
    list:
      - name: Medio Ambiente
      - name: Modelación y simulación de procesos
      - name: Ciencia de datos
      - name: Programación
      - name: Innovación y desarrollo tecnológico
  languages:
    enable: yes
    list:
      - level: Nativo
        name: Español
      - level: Profesional
        name: Inglés
  primaryColor: '#54B689'
  profile:
    avatar: RP.png
    enable: yes
    name: Renán Pulquillanca
    tagline: Ingeniero Civil Químico
  projects:
    enable: yes
    list:
      - meta: Ingeniería - 2019 
        tagline: El objetivo general de este proyecto fue diseñar conceptualmente el proceso productivo de biocombustibles a partir de remolacha azucarera como materia prima. Se desarrolló la organización, el modelo de negocios y la localización virtual de la empresa. Además se describió en detalle el proceso productivo, el diagrama de flujos, el balance de masa y el dimensionamiento final de los equipos. Finalmente, realizar el análisis integral (HAIN) y presentar la responsabilidad social del proyecto.
        title: Diseño y evaluación de la producción de biocombustibles a partir de remolacha azucarera
  skills:
    enable: yes
    list:
      - items:
          - details: R | Python | Matlab | SQL | VBA | DAX
          - details: PowerBi | PowerApps | PowerAutomate
          - details: Excel | Access | MSSQL Server
          - details: PostgreSQL | MySQL Server
          - details: Arcgis | Qgis
          - details: Diseño e implementación de estructuras de base de datos
          - details: Lead and deliver complex software systems
        title: Técnicas
      - items:
          - details: Trabajo en equipo
          - details: Capacidad de resolución de problemas
          - details: Gestión del tiempo
          - details: Ética de trabajo
          - details: Comunicación efectiva
        title: Profesionales
  social:
    enable: yes
    list:
      - icon: fab fa-github-square
        title: Rpulqui
        url: //github.com/Rpulqui
      - icon: fab fa-linkedin
        title: Rpulquillanca
        url: //linkedin.com/in/rpulquillanca
      - icon: fab fa-twitter-square
        title: pulqui_renan
        url: //twitter.com/pulqui_renan
  summary:
    enable: yes
    text: Profesional con experiencia en procesamiento, validación e interpretación de datos hidroquímicos
          de aguas superficiales y subterráneas de diferentes proyectos mineros. 
          Encargado de elaboración de líneas de base componente calidad de aguas, y, posee participación en Declaraciones
          y Estudios de Impacto Ambiental. Posee experiencia en modelación y simulación de procesos con lenguajes de
          programación tales como Matlab y Python. Además, posee sólidos conocimientos en extracción, importación, 
          manipulación, limpieza y visualización de datos en R, Python, Power BI y SQL. Se ha desempeñado como
          administrador de bases de datos en SGA y tiene habilidades de programación para consultas avanzadas en SQL. 
          Ha desarrollado aplicaciones en PowerApps y flujos de trabajo en PowerAutomate para control de proyectos, 
          gestión de carga laboral, gestión técnica unidad de recursos hídricos y sistema gestión de calidad. 
          Además, cuenta con conocimientos de normativas ambientales relacionadas a la calidad del agua y residuos industriales. 
          Por último, posee experiencia en sistemas de información geográfica utilizando R y Arcgis. 
  textPrimaryColor: '#292929'
